version: "2"
services:
    frontend:
            stdin_open: true
            tty: true
            build:
                context: .
            container_name: cake_app
            ports:
                - 3000:3000
                - 3001:3001
            volumes:
                - ./:/approot/
            working_dir: /approot
            environment:
              CAKE_ENDPOINT:  "http://ec2-34-243-153-154.eu-west-1.compute.amazonaws.com:5000/api"
              NODE_ENV: "development"
            entrypoint: sh -cl 'npm install --verbose && npm run watch'